openapi: 3.0.3
info:
  title: Bornali Factoring Finance Limit APIs Definition
  description: |
    # About Limit
    **Limit** Limit refers to the `maximum` amount of financing that a bank or financial institution is willing to provide to a buyer or supplier.
  termsOfService: https://www.spectrum-bd.com/
  x-custom-info:
    comment: Some comments
    developers:
      - name: Bappa Saha
        email: contacts@spectrum-bd.com
      - name: Golam Mostofa
        email: contacts@spectrum-bd.com
  contact:
    name: API Support
    url: https://www.spectrum-bd.com/
    email: contacts@spectrum-bd.com
  license:
    name: Spectrum License
    url: https://www.spectrum-bd.com//licenses/LICENSE-3.0.html
  version: 0.0.1
externalDocs:
  description: |
    ‚û°Ô∏è Here is the üìÑ YML file Code link
  url: https://github.com/bappasahabapi/bappasahabapi.github.io/blob/main/openapi.yml

servers:
  - url: http://localhost:5000/api/v1/factoring-finance/limit
    description: Development server
  - url: https://xyz.server.com
    description: Production server
  - url: https://xyz.tesing.com/api/v1/factoring-finance/limit
    description: Testing server
tags:
  - name: Limit
    description: Factoring Finance `Limit` related operations
security:
  - BearerAuthToken: []
  - BasicAuth: []
  - ApiKeyAuth: []
  - oAuth2AuthCode:
      - read
      - write
      - admin
paths:
  /limit:
    get:
      operationId: getLimits
      tags:
        - Limit
      summary: Get Default Limit Data
      description: This API returns all the **default information** for the limit setup.
      parameters:
        - $ref: "#/components/parameters/pageParam"
        - $ref: "#/components/parameters/limitParam"
        - $ref: "#/components/parameters/sortTypeParam"
        - $ref: "#/components/parameters/sortByParam"
        - $ref: "#/components/parameters/searchParam"
      responses:
        "200":
          description: Default information for the limit setup.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LimitSchema"
              examples:
                default-data:
                  summary: Default Limit data
                  value:
                    data:
                      scfProductCode: "1"
                      creditPeriod: "90"
                      financingRate: "80.00"
                      gracePeriod: "10"
                      penaltyRate: "9.00"
                      interestRate: "9.00"
                      invoiceProcessingRate: "0.20"
                      safetyDepositRate: "2.00"
                    messageCode: ""
        "500":
          $ref: "#/components/responses/500"

    post:
      operationId: createLimit
      tags: [Limit]
      summary: Create Limit API
      description: |
        This API creates a new limit for the supplier and buyers.
      requestBody:
        description: To create a new limit` Cad Maker` needs to provide valid input data
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestBodySchema"
      responses:
        "201":
          description: Successfully created a new article
          content:
            "application/json":
              schema:
                type: object
                properties:
                  messageCode:
                    type: string
                    example: "Limit Created Successfully ."
          # description: Successfully created a new article
          # content:
          #   "application/json":
          #     schema:
          #       $ref: '#/components/schemas/RequestBodySchema'
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "500":
          $ref: "#/components/responses/500"
    put:
      operationId: updateLimit
      tags: [Limit]
      summary: Update Limit API
      description: |
        This API updates the submitted limit request by ID.
      requestBody:
        description: To create a new limit` Cad Maker` needs to provide valid input data
        content:
          application/json:
            schema:
              type: object
              properties:
                buyerLimitList:
                  type: array
                  items:
                    $ref: "#/components/schemas/UpdateBuyerLimit"
                deletedBuyerLimitIds:
                  type: array
                  items:
                    type: string
                  example: []
                isPOwise:
                  type: boolean
                  example: false
                showModal:
                  type: boolean
                  example: false
                isManual:
                  type: boolean
                  example: true
                startDate:
                  type: integer
                  format: int64
                  example: 0
                endDate:
                  type: integer
                  format: int64
                  example: 0
                status:
                  type: string
                  example: "Pending"
                dateCategory:
                  type: string
                  example: ""
                id:
                  type: string
                  example: "e62772ba-03c7-4a03-82b1-636d8f8f82bc"
                wfId:
                  type: string
                  example: "222"
                scfProductCode:
                  type: string
                  example: "1"
                supplierId:
                  type: string
                  example: "003"
                supplierName:
                  type: string
                  example: "Banglalink"
                supplierAddress:
                  type: string
                  example: "456 Elm Avenue"
                totalCreditLimit:
                  type: string
                  example: "1000000.00"
                loanAccount:
                  type: string
                  example: "87967833569"
                cdAccount:
                  type: string
                  example: "87967833568"
                assignmentAccount:
                  type: string
                  example: "87967833570"
                branchId:
                  type: string
                  example: "1003"
                branchName:
                  type: string
                  example: "Banasree"
                rmId:
                  type: string
                  example: "2222"
                rmName:
                  type: string
                  example: "Mithu"
                disbursementDate:
                  type: integer
                  format: int64
                  example: 1710007200000
                penaltyRate:
                  type: string
                  example: "9.00"
                interestRate:
                  type: string
                  example: "9.00"
                invoiceProcessingRate:
                  type: string
                  example: "0.20"
                safetyDepositRate:
                  type: string
                  example: "2.00"
                supplierFinancingRate:
                  type: string
                  example: "80.00"
                maxRoleId:
                  type: string
                  example: "2e8e6d3c-930d-4b60-8c25-7e4d6b326d2c"
                statusId:
                  type: string
                  example: "f8c772bd-7900-4e3f-a023-2e93dab5ac2a"
                expiryDate:
                  type: string
                  example: "10/03/2025"
                motherLimitId:
                  type: string
                  example: "e62772ba-03c7-4a03-82b1-636d8f8f82bc"
                addressId:
                  type: string
                  example: "a3e0aae9-2ec6-4f5e-8ba9-1d79c45c7881"
                supplierCode:
                  type: string
                  example: "4003"
      responses:
        "201":
          description: Successfully created a new article
          content:
            "application/json":
              schema:
                type: object
                properties:
                  messageCode:
                    type: string
                    example: "Limit Updated Successfully ."
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "500":
          $ref: "#/components/responses/500"

  /branches:
    get:
      tags:
        - Limit
      summary: Get Branch List API
      description: This API returns branch data
      security:
        - BasicAuth: []
      responses:
        "200":
          description: Branch Data information for the limit setup.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BranchSchema"
              examples:
                default-data:
                  summary: Default branch data
                  value:
                    data:
                      - id: 1001
                        name: "Banani"
                      - id: 1002
                        name: "Ashulia"
                      - id: 1003
                        name: "Banasree"
                      - id: 1004
                        name: "Dhanmondi"
                    messageCode: ""
        "500":
          $ref: "#/components/responses/500"
  /companies:
    get:
      tags:
        - Limit
      summary: This API returns company data
      security:
        - BasicAuth: []
      responses:
        "200":
          description: Companies Data information for limit set up.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompanySchema"
              examples:
                default-data:
                  summary: Default company information
                  value:
                    data:
                      - id: 001
                        name: GP
                      - id: CBS-004
                        name: Rancon Motorbikes
                    messageCode: ""
        "500":
          $ref: "#/components/responses/500"
  /find:
    post:
      tags:
        - Limit
      summary: Get Filtered Limit List API
      description: |
        This API returns the list of requested limits filtered by the requested data.
      parameters:
        - $ref: "#/components/parameters/requestParam"

      responses:
        "200":
          description: Limit Fetched Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LimitListResBodySchema"
              examples:
                default-data:
                  summary: Default data example
                  value:
                    data:
                      - id: "87ba40b2-18cc-4514-b881-573daaa1a4b5"
                        supplierId: "001"
                        supplierName: "Bismillah Enterprise"
                        creditLimit: "1000000.00"
                        rmName: "Mithu"
                        rmId: "f8c772bd-7900-4e3f-a023-2e93dab5ac2a"
                        branchId: "f8c772bd-7900-4e3f-a023-2e93dab5ac2a"
                        branchName: "Banani"
                        disbursementDate: "1710007200000"
                        remarks: null
                        wf_id: "217"
                        status: "Done"
                        maxRoleId: "2e8e6d3c-930d-4b60-8c25-7e4d6b326d2c"
                        maxRoleName: "CAD Authorizer"
                        total_count: "1"
                        row_num: "1"
                    totalPages: 1
                    totalCounts: 1
                    messageCode: ""
        "500":
          $ref: "#/components/responses/500"
  /supplier/{id}:
    get:
      tags: [Limit]
      summary: Get Supplier Limit Data by Supplier ID
      description: This API returns the supplier data for the provided ID.
      parameters:
        - $ref: "#/components/parameters/supplierIdPathParam"
      responses:
        "200":
          description: Order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      supplierName:
                        type: string
                        example: Banglalink
                      addressId:
                        type: string
                        example: a3e0aae9-2ec6-4f5e-8ba9-1d79c45c7881
                      supplierCode:
                        type: string
                        format: int32
                        example: 4003
                      supplierAddress:
                        type: string
                        example: 456 Elm Avenue
                      cdAccount:
                        type: string
                        example: 87967833569
                      loanAccount:
                        type: string
                        example: 87967833569
                      assignmentAccount:
                        type: string
                        example: "87967833570"
                      motherLimitId:
                        type: string
                        example: null

                  messageCode:
                    type: string
                    example: ""

              # examples:
              #   default-data:
              #     summary: Default data example
              #     value:
              #       data:
              #       #   - id: "87ba40b2-18cc-4514-b881-573daaa1a4b5"
              #       #     supplierId: "001"
              #       #     supplierName: "Bismillah Enterprise"
              #       #     creditLimit: "1000000.00"
              #       #     rmName: "Mithu"
              #       #     rmId: "f8c772bd-7900-4e3f-a023-2e93dab5ac2a"
              #       #     branchId: "f8c772bd-7900-4e3f-a023-2e93dab5ac2a"
              #       #     branchName: "Banani"
              #       #     disbursementDate: "1710007200000"
              #       #     remarks: null
              #       #     wf_id: "217"
              #       #     status: "Done"
              #       #     maxRoleId: "2e8e6d3c-930d-4b60-8c25-7e4d6b326d2c"
              #       #     maxRoleName: "CAD Authorizer"
              #       #     total_count: "1"
              #       #     row_num: "1"
              #       # totalPages: 1
              #       # totalCounts: 1
              #       messageCode: ""
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /cbs-supplier-limit-data/{supplierCbsId}/{loanAccount}:
    get:
      tags: [Limit]
      summary: Get CBS Supplier Limit Data API
      description: This API returns the details of requested supplier data according to the supplier id and loan account
      parameters:
        - $ref: "#/components/parameters/cbsIdPathParam"
        - in: path
          required: true
          name: loanAccount
          description: Loan account number according to the supplier cbs id
          schema:
            type: string
            example: 123-456
      responses:
        "200":
          description: Fetched data successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      assignmentAccount:
                        type: string
                        example: "123-321-456"
                      cdAccount:
                        type: string
                        example: "456-789-987"
                      scfProductCode:
                        type: string
                        example: "1"
                      supplierName:
                        type: string
                        example: "Bismillah Enterprise-1"
                      supplierAddress:
                        type: string
                        example: "123 Gulshan"
                      branchId:
                        type: string
                        example: "1001"
                      branchName:
                        type: string
                        example: "Mohakhali Branch"
                      rmId:
                        type: string
                        example: "2222"
                      rmName:
                        type: string
                        example: "Mr Jalal Uddin"
                      disbursementDate:
                        type: string
                        example: 1711607933625
                      addressId:
                        type: string
                        example: "f8c772bd-7900-4e3f-a023-2e93dab5ac2a"
                      totalCreditLimit:
                        type: string
                        example: 10000000
                  messageCode:
                    type: string
                    example: ""
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /anchor-limit-info/{anchorCbsId}}:
    get:
      tags: [Limit]
      summary: Get Limit Amount Info Data  API
      description: This API returns the **limit amount info data** .
      parameters:
        - in: path
          required: true
          name: anchorCbsId
          description: Anchor limit info according to the `anchorCbsId` will be returned.
          schema:
            type: string
            example: "001"
      responses:
        "200":
          description: Fetched data successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      factoringNotionalLimit:
                        type: string
                        example: "1000000"
                      anchorCumulativeLimit:
                        type: string
                        example: "400000.00"

                  messageCode:
                    type: string
                    example: ""
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /id/{id}:
    get:
      tags: [Limit]
      summary: Get Limit Details API
      description: This API returns the details of requested limit.
      parameters:
        - in: path
          required: true
          name: id
          description: Limit details according to the `id` will be returned.
          schema:
            type: string
            example: "87ba40b2-18cc-4514-b881-573daaa1a4b5"
      responses:
        "200":
          description: Fetched limit details data successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "3e424c21-01a1-42fb-980d-53999cdf03d5"
                      wfId:
                        type: string
                        example: "331"
                      scfProductCode:
                        type: string
                        example: "1"
                      supplierId:
                        type: string
                        example: "CBS-003"
                      supplierName:
                        type: string
                        example: "ABC Enterprises"
                      supplierAddress:
                        type: string
                        example: "city town"
                      totalCreditLimit:
                        type: string
                        example: "2000000.00"
                      loanAccount:
                        type: string
                        example: "234-234-234"
                      cdAccount:
                        type: string
                        example: "123-456-789"
                      assignmentAccount:
                        type: string
                        example: "987-654-321"
                      branchId:
                        type: string
                        example: "1001"
                      branchName:
                        type: string
                        example: "Banani"
                      rmId:
                        type: string
                        example: "2222"
                      rmName:
                        type: string
                        example: "Mithu"
                      disbursementDate:
                        type: string
                        example: "1713290400000"
                      penaltyRate:
                        type: string
                        example: "9.00"
                      interestRate:
                        type: string
                        example: "9.00"
                      invoiceProcessingRate:
                        type: string
                        example: "0.20"
                      safetyDepositRate:
                        type: string
                        example: "2.00"
                      otherCharge:
                        type: string
                        example: null
                      supplierFinancingRate:
                        type: string
                        example: "80.00"
                      supplierMakerEmail:
                        type: string
                        example: "1234567890"
                      supplierMakerContact:
                        type: string
                        example: "b@gmail.com"
                      supplierAuthorizerEmail:
                        type: string
                        example: null
                      supplierAuthorizerContact:
                        type: string
                        example: null
                      isSlb:
                        type: string
                        example: null
                      isInvoice:
                        type: string
                        example: null
                      isEmail:
                        type: string
                        example: null
                      isSms:
                        type: string
                        example: null
                      status:
                        type: string
                        example: "Pending"
                      maxRoleId:
                        type: string
                        example: "2e8e6d3c-930d-4b60-8c25-7e4d6b326d2c"
                      statusId:
                        type: string
                        example: "f8c772bd-7900-4e3f-a023-2e93dab5ac2a"
                      buyerDetails:
                        $ref: "#/components/schemas/BuyerDetailsSchema"

                  messageCode:
                    type: string
                    example: ""
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /limit/limit-status:
    put:
      operationId: updateLimitStatus
      tags: [Limit]
      summary:  Update Limit Status API
      description: |
       This API updates the limit status 
      requestBody:
        description: To create a new limit` Cad Maker` needs to provide valid input data
        content:
          application/json:
            schema:
             type: array
             items:
                type: object
                properties:
                  id:
                    type: string
                    example: "5aa53eed-a83b-44f9-aac0-e7601aef697d"
                  statusId:
                    type: string
                    example: "2"
      responses:
        "201":
          description: Limit Status Update Successfully
          content:
            "application/json":
              schema:
                type: object
                properties:
                  messageCode:
                    type: string
                    example: "Limit Status Updated Successfully ."
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "500":
          $ref: "#/components/responses/500"

# ------------------------------ Reusable Components -----------------------

components:
  # ------------------------------ Schemas -----------------------
  schemas:
    LimitSchema:
      type: object
      properties:
        data:
          type: object
          properties:
            scfProductCode:
              type: integer
              format: int32
            creditPeriod:
              type: integer
            financingRate:
              type: number
              format: double
            gracePeriod:
              type: integer
            penaltyRate:
              type: number
              format: double
            interestRate:
              type: number
              format: double
            invoiceProcessingRate:
              type: number
              format: double
            safetyDepositRate:
              type: number
              format: double
        messageCode:
          type: string
    BranchSchema:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
    CompanySchema:
      type: object
      properties:
        id:
          type: integer
          format: string
        name:
          type: string
    LimitListResBodySchema:
      type: object
      properties:
        data::
          type: object
          properties:
            data:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  supplierId:
                    type: string
                  supplierName:
                    type: string
                  creditLimit:
                    type: string
                  rmName:
                    type: string
                  rmId:
                    type: string
                  branchId:
                    type: string
                  branchName:
                    type: string
                  disbursementDate:
                    type: string
                  remarks:
                    type: string
                    nullable: true
                  wf_id:
                    type: string
                  status:
                    type: string
                  maxRoleId:
                    type: string
                  maxRoleName:
                    type: string
                  total_count:
                    type: string
                  row_num:
                    type: string
            totalPages:
              type: integer
            totalCounts:
              type: integer
        messageCode:
          type: string
    BuyerDetailsSchema:
      type: array
      items:
        type: object
        properties:
          buyerTrackingId:
            type: string
            example: "35382d31-33f1-461b-b18d-171819cf2a99"
          buyerId:
            type: string
            example: "001"
          buyerCreditLimit:
            type: string
            example: "200000.00"
          buyerOnboardingDate:
            type: string
            example: "1713290400000"
          creditPeriod:
            type: string
            example: "90"
          buyerFinancingRate:
            type: string
            example: "80.00"
          buyerMakerEmail:
            type: string
            example: "a@gmail.com"
          buyerMakerContact:
            type: string
            example: "098765431"
          buyerAuthorizerEmail:
            type: string
            example: "buyer@gmail.com"
          buyerAuthorizerContact:
            type: string
            example: "1234567890"
          buyerName:
            type: string
            example: "GP"
    DetailsSchema:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              example: "3e424c21-01a1-42fb-980d-53999cdf03d5"
            wfId:
              type: string
              example: "331"
            scfProductCode:
              type: string
              example: "1"
            supplierId:
              type: string
              example: "CBS-003"
            supplierName:
              type: string
              example: "ABC Enterprises"
            supplierAddress:
              type: string
              example: "city town"
            totalCreditLimit:
              type: string
              example: "2000000.00"
            loanAccount:
              type: string
              example: "234-234-234"
            cdAccount:
              type: string
              example: "123-456-789"
            assignmentAccount:
              type: string
              example: "987-654-321"
            branchId:
              type: string
              example: "1001"
            branchName:
              type: string
              example: "Banani"
            rmId:
              type: string
              example: "2222"
            rmName:
              type: string
              example: "Mithu"
            disbursementDate:
              type: string
              example: "1713290400000"
            penaltyRate:
              type: string
              example: "9.00"
            interestRate:
              type: string
              example: "9.00"
            invoiceProcessingRate:
              type: string
              example: "0.20"
            safetyDepositRate:
              type: string
              example: "2.00"
            otherCharge:
              type: string
              example: null
            supplierFinancingRate:
              type: string
              example: "80.00"
            supplierMakerEmail:
              type: string
              example: "1234567890"
            supplierMakerContact:
              type: string
              example: "b@gmail.com"
            supplierAuthorizerEmail:
              type: string
              example: null
            supplierAuthorizerContact:
              type: string
              example: null
            isSlb:
              type: string
              example: null
            isInvoice:
              type: string
              example: null
            isEmail:
              type: string
              example: null
            isSms:
              type: string
              example: null
            status:
              type: string
              example: "Pending"
            maxRoleId:
              type: string
              example: "2e8e6d3c-930d-4b60-8c25-7e4d6b326d2c"
            statusId:
              type: string
              example: "f8c772bd-7900-4e3f-a023-2e93dab5ac2a"
    RequestBodySchema:
      type: object
      properties:
        isPOwise:
          type: boolean
          example: false
        showModal:
          type: boolean
          example: false
        isManual:
          type: boolean
          example: true
        startDate:
          type: integer
          format: int64
          example: 0
        endDate:
          type: integer
          format: int64
          example: 0
        id:
          type: string
          example: ""
        scfProductCode:
          type: string
          example: "1"
        creditPeriod:
          type: string
          example: "90"
        financingRate:
          type: string
          example: "80.00"
        gracePeriod:
          type: string
          example: "10"
        penaltyRate:
          type: string
          example: "9.00"
        interestRate:
          type: string
          example: "9.00"
        invoiceProcessingRate:
          type: string
          example: "0.20"
        safetyDepositRate:
          type: string
          example: "2.00"
        disbursementDate:
          type: integer
          format: int64
          example: 1710093600000
        expiryDate:
          type: string
          example: "11/03/2025"
        supplierFinancingRate:
          type: string
          example: "80.00"
        buyerOnboardingDate:
          type: string
          example: "11/03/2024"
        supplierId:
          type: string
          example: "001"
        supplierName:
          type: string
          example: "Bismillah Enterprise"
        addressId:
          type: string
          example: "f8c772bd-7900-4e3f-a023-2e93dab5ac2a"
        supplierCode:
          type: string
          example: "4001"
        supplierAddress:
          type: string
          example: "123 Main Street"
        cdAccount:
          type: string
          example: "87967833562"
        loanAccount:
          type: string
          example: "87967833563"
        assignmentAccount:
          type: string
          example: "87967833564"
        motherLimitId:
          type: string
          example: null
        branchId:
          type: string
          example: "1001"
        branchName:
          type: string
          example: "Banani"
        totalCreditLimit:
          type: integer
          example: 1000000
        rmId:
          type: string
          example: "2222"
        rmName:
          type: string
          example: "Mithu"
        buyerId:
          type: string
          example: "002"
        buyerName:
          type: string
          example: "Robi55"
        buyerCreditLimit:
          type: integer
          example: 200000
        buyerFinancingRate:
          type: string
          example: "80.00"
        buyerTrackingId:
          type: integer
          example: 1710131127726
        authorizer:
          type: string
          example: "cad_authorizer"
        authorizerId:
          type: string
          example: "a5366fe7-5e85-4dfb-9e18-02685330c421"
        authorizerName:
          type: string
          example: "cad_authorizer"
        buyerLimitList:
          type: array
          items:
            $ref: "#/components/schemas/BuyerLimit"
        wfProjectId:
          type: integer
          example: 3
        wfStartDate:
          type: integer
          format: int64
          example: 1710131136790

    BuyerLimit:
      type: object
      properties:
        buyerTrackingId:
          type: integer
          example: 1710131127726
        buyerId:
          type: string
          example: "002"
        buyerName:
          type: string
          example: "Robi55"
        buyerCreditLimit:
          type: integer
          example: 200000
        buyerOnboardingDate:
          type: integer
          format: int64
          example: 1710093600000
        buyerFinancingRate:
          type: string
          example: "80.00"
        creditPeriod:
          type: string
          example: "90"

    UpdateBuyerLimit:
      type: object
      properties:
        buyerTrackingId:
          type: string
          example: "c956b162-f8bf-4b0b-a199-fed15256a8a9"
        buyerId:
          type: string
          example: "006"
        buyerCreditLimit:
          type: string
          example: "200000.00"
        buyerOnboardingDate:
          type: integer
          format: int64
          example: 1710007200000
        creditPeriod:
          type: string
          example: "90"
        buyerFinancingRate:
          type: string
          example: "80.00"
        buyerName:
          type: string
          example: "Microsoft Corporation"

  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuthToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
    oAuth2AuthCode:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/api/oauth.access
          scopes:
            read: Read only access
            write: Read Write access
            admin: Admin access

  # ------------------------------ responses -----------------------
  responses:
    "500":
      description: Internal server error
      content:
        "application/json":
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
                example: 500
              error:
                type: string
                example: Internal server error
              message:
                type: string
                example: Database is not accessible or there is an internal error Please try again later.
    "400":
      description: Bad request
      content:
        "application/json":
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
                example: 400
              error:
                type: string
                example: Bad request
              # data:
              #   type: array
              #   items:
              #     type: object
              #     properties:
              #       field:
              #         type: string
              #         example: email
              #       message:
              #         type: string
              #         example: Invalid email
              #       in:
              #         type: string
              #         enum: [query, body]
              #         example: body
    "401":
      description: Unauthorized
      content:
        "application/json":
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
                example: 401
              error:
                type: string
                example: Unauthorized
              message:
                type: string
                example: You don't have the right permission.
    "404":
      description: Not Found
      content:
        "application/json":
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
                example: 404
              error:
                type: string
                example: Not Found
              message:
                type: string
                example: Data not found belonging to this id
  # responses:
  #   InternalServerError:
  #     description: |
  #       An error occurred while processing the request.
  #       Please contact support@specreum.com

  # ------------------------------ parameters -----------------------

  parameters:
    pageParam:
      in: query
      name: page
      description: Current page number
      schema:
        type: integer
        format: int32
        example: 1
    limitParam:
      in: query
      name: limit
      description: Maximum items to be returned
      schema:
        type: integer
        format: int32
        example: 10
    sortTypeParam:
      in: query
      name: sort_type
      description: Type of sort (asc or dsc)
      schema:
        type: string
        enum: [asc, dsc]
        example: dsc
    sortByParam:
      in: query
      name: sort_by
      description: Sort key
      schema:
        type: string
        example: updatedAt
    searchParam:
      in: query
      name: search
      description: Search term
      schema:
        type: string
        enum:
          - title
          - id
          - status
        example: title
    requestParam:
      in: query
      name: search
      description: Search term
      schema:
        type: string
        enum:
          - search
          - dateCategory
          - startDate
          - endDate
          - status
          - currentPage
          - size
          - scfProductId
        example: status
    supplierIdPathParam:
      in: path
      name: id
      required: true
      description: Supplier Data belonging to `id` will be returned
      schema:
        type: integer
        format: int32
        example: 003
    cbsIdPathParam:
      in: path
      name: supplierCbsId
      required: true
      description: Supplier Data belonging to `id` will be returned
      schema:
        type: string
        example: S-001
